109 connect the forms on our webpages to hit our api accordingly
obscuritylabs/darkmoon pull request #122
Opened 2023-08-03 21:00 UTC by XxXgamerguyXxX

# Pull request

**Resolves:** #<<109>>

2023-08-07 20:44 UTC, asmitakarandikar commented
The text box that displays results is showing up on Safari, but it is not showing up on Chrome.

2023-08-08 18:25 UTC, pelavarthi submitted a review, later dismissed
Looks god

2023-08-08 18:43 UTC, DoodlePooge requested changes

2023-08-08 18:43 UTC, DoodlePooge commented on darkmoon/api/templates/credit.html
Remove this from this PR, this is not for this ticket.

2023-08-08 18:43 UTC, DoodlePooge commented on package-lock.json
do we need this?

2023-08-08 19:45 UTC, DoodlePooge approved these changes

2023-08-08 19:47 UTC, merged