52 new mt
obscuritylabs/darkmoon pull request #123
Opened 2023-08-04 20:08 UTC by thulasiramanmt

# Pull request

**Resolves:** #52

2023-08-04 20:33 UTC, pelavarthi approved these changes

2023-08-04 20:33 UTC, pelavarthi commented on darkmoon/api/backend/endpoint.py
> +    """Docstring."""
Missing docstring

2023-08-04 20:33 UTC, pelavarthi commented on darkmoon/api/backend/endpoint.py
> +    source_iso: UploadFile = File(...),
Check object type for source_iso. Might need to make it a string.

2023-08-04 20:33 UTC, pelavarthi commented on darkmoon/common/utils.py
> +        if result.returncode != 0:
Should it be result.status code?

2023-08-04 20:39 UTC, pelavarthi submitted a review, later dismissed

2023-08-07 14:36 UTC, DoodlePooge requested changes

2023-08-07 14:36 UTC, DoodlePooge commented on darkmoon/api/backend/endpoint.py
>      source_iso: PyPath = PyPath("..."),
How come some parameters for source_iso take in a path while other take UploadFile?

2023-08-07 14:36 UTC, DoodlePooge commented on darkmoon/api/backend/endpoint.py
>  async def extract_files_endpoint(
This endpoint fails with the proper parameters provided.

2023-08-07 16:30 UTC, DoodlePooge submitted a review, later dismissed

2023-08-07 17:19 UTC, DoodlePooge approved these changes

2023-08-07 17:39 UTC, merged