119 create credits webpage mt
obscuritylabs/darkmoon pull request #142
Opened 2023-08-09 20:31 UTC by thulasiramanmt

# Pull request

**Resolves:** #<<issue number>>

2023-08-09 21:20 UTC, XxXgamerguyXxX commented
looks good

2023-08-10 16:02 UTC, DoodlePooge requested changes
The navbar does not properly navigate to the credits page

2023-08-10 18:22 UTC, Viraj-Ganguli approved these changes

2023-08-10 18:23 UTC, DoodlePooge approved these changes

2023-08-10 18:24 UTC, merged