feat: Jinja connected to fastAPI, added 'darkmoon', 'fastapi', and 't…
obscuritylabs/darkmoon pull request #45
Opened 2023-07-07 18:16 UTC by thulasiramanmt

…emplating' to the workspace dictionary

# Pull request

**Resolves:** #<<issue number>>

2023-07-07 20:06 UTC, Viraj-Ganguli submitted a review, later dismissed
Looks good! @DoodlePooge This seems ready for review.

2023-07-10 13:56 UTC, tclasen requested changes

2023-07-10 13:56 UTC, tclasen commented on darkmoon/app.py
> +app = FastAPI()
FastAPI app creation already happens later in this file, please remove this line

2023-07-10 13:56 UTC, tclasen commented on darkmoon/app.py
> +templates = Jinja2Templates(directory="templates")
Please move the templates direction into the FastAPI application factory.

2023-07-10 13:56 UTC, tclasen commented on darkmoon/app.py
> +@app.get("/items/{id}", response_class=HTMLResponse)
Please move this route into the FastAPI application factory below.

2023-07-10 13:56 UTC, tclasen commented on darkmoon/Jinja.py
Please delete this whole file, it isn't needed.

2023-07-10 20:06 UTC, Viraj-Ganguli approved these changes
Looks good, Pranav and I approve.

2023-07-11 14:26 UTC, DoodlePooge commented
If the current code does work it is not clear on how it's supposed to work.

2023-07-13 20:07 UTC, closed without merging