37 have the post endpoint return a success message and the object that was posted to the db
obscuritylabs/darkmoon pull request #47
Opened 2023-07-07 18:57 UTC by Synthint

# Pull request

**Resolves:** #37

2023-07-07 20:20 UTC, asmitakarandikar commented
Just reviewed this PR and it looks good on my end. The post endpoint is returning a success message and the object is successfully posted to the database.

2023-07-10 13:40 UTC, tclasen approved these changes

2023-07-10 14:05 UTC, DoodlePooge requested changes

2023-07-10 14:05 UTC, DoodlePooge commented on darkmoon/api/v1/metadata/schema.py
> +    )
Change the term from object to data since it's more standard. You are not always getting 1 object, sometimes it's a list.

2023-07-10 15:52 UTC, DoodlePooge submitted a review, later dismissed

2023-07-10 19:58 UTC, DoodlePooge approved these changes

2023-07-11 13:34 UTC, merged