Add Exception Response for file upload in place of HTTPExcceptions
obscuritylabs/darkmoon pull request #48
Opened 2023-07-07 19:17 UTC by Viraj-Ganguli

# Pull request

**Resolves:** #<<44>>

2023-07-10 13:41 UTC, tclasen requested changes

2023-07-10 13:41 UTC, tclasen commented on darkmoon/api/v1/metadata/Exception_Response.py
> +class Missing_Hash_Exception(Exception):
Please remove underscores from all class names in accordance with[PEP8](https://peps.python.org/pep-0008/#class-names)

2023-07-10 13:41 UTC, tclasen commented on poetry.lock
@DoodlePooge , why did this lockfile change so much?

2023-07-10 15:32 UTC, asmitakarandikar commented
Just reviewed this PR and it looks good on my end. It is successfully using Exception Response to throw exceptions.

2023-07-11 14:08 UTC, DoodlePooge requested changes

2023-07-11 14:08 UTC, DoodlePooge commented on darkmoon/app.py
> +    @app.exception_handler(ServerNotFoundException)
This seems like an excessive solution for setting up your Exceptions. What I'm looking for is to utilize the HTTPException model and create Exceptions that can be grouped by similar types. This ticket is for code clarity, we don't need this.

2023-07-11 14:08 UTC, DoodlePooge commented on darkmoon/api/v1/metadata/Exception_Response.py
> +class MissingHashException(Exception):
I want created Exceptions for inherit the HTTPException model so that we still have the status_code and detail fields.

2023-07-12 13:23 UTC, closed without merging