36 update and cleanup docstrings
obscuritylabs/darkmoon pull request #51
Opened 2023-07-10 18:47 UTC by asmitakarandikar

# Pull request

**Resolves:** #36

2023-07-10 20:08 UTC, Viraj-Ganguli approved these changes
Pranav and I took a look and it looks good. We appreciate the verbosity!

2023-07-12 18:59 UTC, DoodlePooge requested changes

2023-07-12 18:59 UTC, DoodlePooge commented on darkmoon/api/v1/metadata/schema.py
> +"""Import module/class PydanticObjectID, BaseModel, and Field"""
This did not need to be moved. In fact, the docstring itself at the top should more so explain the purpose of the file itself. Imports don't need docstrings

2023-07-12 18:59 UTC, DoodlePooge commented on darkmoon/api/v1/metadata/views.py
> + beanie, APIRouter, Depends, HTTPException, Query from fastapi, AsyncIOMotorCollection
Again not necessary

2023-07-12 18:59 UTC, DoodlePooge commented on darkmoon/api/v1/metadata/views.py
> +"""This is the views.py file."""
If we are keeping these docstrings at the top, they need to be more useful than stating the name of the file.

2023-07-12 18:59 UTC, DoodlePooge commented on darkmoon/api/v1/metadata/views.py
> +    """List of metadata that matches the parameters in the database.
This endpoint is not a list, but it grabs a list. You can say something like Get list

2023-07-12 18:59 UTC, DoodlePooge commented on darkmoon/api/v1/metadata/views.py
> +    """Fast API post function for incoming files.
"Adds metadata from files to the database"
Saying that this is a FastAPI POST function is redundant.

2023-07-12 18:59 UTC, DoodlePooge commented on darkmoon/api/v1/metadata/views.py
Docstrings should also provide any exceptions the function raises.

2023-07-12 18:59 UTC, DoodlePooge commented on darkmoon/app.py
> +    """Return the FastAPI connection."""
Is this accurate to the function's purpose?

2023-07-12 18:59 UTC, DoodlePooge commented on darkmoon/cli/main.py
Again, the top of the file docstring should give a developer an idea of what this file provides to the project. What is the main.py file? why is it?

2023-07-12 18:59 UTC, DoodlePooge commented on darkmoon/cli/main.py
> +    """Call the get metadata function from utils.py and send data to api endpoint."""
For all of these, you don't need to say exactly what is run. The docstring should give a general purpose, parameters, raises (exceptions), and returns

2023-07-12 18:59 UTC, DoodlePooge commented on requirements.txt
please delete this

2023-07-12 18:59 UTC, DoodlePooge commented on pyproject.toml
> +jinja2 = "^3.1.2"
Why is this added in the docstring ticket?

2023-07-12 18:59 UTC, DoodlePooge commented on pyproject.toml
> +jinja2 = "^3.1.2"
it's not bad but it means you're pulling changes from other places which is just a bad habit

2023-07-12 19:00 UTC, DoodlePooge commented
There are also still unverified commits, these need to be fixed or we can't merge it in.

2023-07-13 20:07 UTC, closed without merging