chore: fixing the commit to make it verified
obscuritylabs/darkmoon pull request #61
Opened 2023-07-13 19:36 UTC by thulasiramanmt

# Pull request

**Resolves:** #<<issue number>>

2023-07-14 15:35 UTC, DoodlePooge commented
What is this PR for?

2023-07-14 20:47 UTC, thulasiramanmt commented
> What is this PR for?
it's for #36

2023-07-14 20:50 UTC, pelavarthi submitted a review, later dismissed
reviewed and it looks okay to me

2023-07-17 13:52 UTC, Viraj-Ganguli reviewed
Still looks good after merging with main!

2023-07-17 17:38 UTC, pelavarthi commented
looks okay to me

2023-07-18 19:26 UTC, Viraj-Ganguli approved these changes
Looks good!

2023-07-18 20:00 UTC, DoodlePooge requested changes

2023-07-18 20:00 UTC, DoodlePooge commented on darkmoon/api/v1/metadata/views.py
>          IncorrectInputException:
Raises Raises Raises...

2023-07-18 20:00 UTC, DoodlePooge commented on darkmoon/app.py
No.

2023-07-18 21:32 UTC, DoodlePooge requested changes

2023-07-18 21:32 UTC, DoodlePooge commented on README.md
This is not the readme PR

2023-07-18 21:32 UTC, DoodlePooge commented on darkmoon/app.py
This was not resolved. Jinja logic is still here...

2023-07-18 21:32 UTC, DoodlePooge commented on darkmoon/app.py
> -    app = FastAPI()
Why are you removing code?

2023-07-19 13:40 UTC, Viraj-Ganguli approved these changes
Looks good!

2023-07-19 14:47 UTC, Viraj-Ganguli reviewed
Looks good!

2023-07-19 14:57 UTC, DoodlePooge requested changes

2023-07-19 14:57 UTC, DoodlePooge commented on darkmoon/api/v1/metadata/views.py
> +        errors.ServerSelectionTimeoutError: If the server is not found.
Not being raised anymore

2023-07-19 19:22 UTC, Viraj-Ganguli reviewed
Looks good!

2023-07-19 19:49 UTC, DoodlePooge requested changes

2023-07-19 19:49 UTC, DoodlePooge commented on README.md
> -
Please put these lines back

2023-07-19 19:49 UTC, DoodlePooge commented on darkmoon/api/v1/metadata/views.py
>              Endpoint is unable to connect to mongoDB instance
This should be under a raises section along with the other exceptions for this endpoint

2023-07-19 19:49 UTC, DoodlePooge commented on darkmoon/api/v1/metadata/views.py
> +        errors.ServerSelectionTimeoutError: If the server is not found.
This was not resolved, why are we resolving issues that are not resolved? HTTPException is not called in this function anymore.

2023-07-19 19:49 UTC, DoodlePooge commented on darkmoon/api/v1/metadata/views.py
What is going on with that CLASSES comment block? remove it or fix it.

2023-07-19 19:49 UTC, DoodlePooge commented on darkmoon/api/v1/metadata/views.py
Also for my sanity's sake, keep all your docstrings in the same order, pick either Parameters -> Raises -> Returns OR Parameters -> Returns -> Raises
Stop doing both orderings

2023-07-19 20:27 UTC, Viraj-Ganguli reviewed
Looks good!

2023-07-19 20:38 UTC, DoodlePooge approved these changes

2023-07-19 20:42 UTC, merged