feat: fixed commits
obscuritylabs/darkmoon pull request #83
Opened 2023-07-18 20:10 UTC by thulasiramanmt

# Pull request

**Resolves:** #74

2023-07-18 20:39 UTC, DoodlePooge requested changes

2023-07-19 13:32 UTC, pelavarthi approved these changes
looks good

2023-07-19 15:24 UTC, DoodlePooge requested changes

2023-07-19 15:24 UTC, DoodlePooge commented on README.md
> + The Web API service will utilize FastAPI. This web service will be un-authenticated and allow for reading and writing. Lookups will be able to search by name or hashes (MD5, SHA1, SHA128, SHA256) ut
Why are there spaces beginning each line.

2023-07-19 16:52 UTC, DoodlePooge approved these changes

2023-07-19 17:16 UTC, merged